# Stage 1: Build
FROM gradle:7.5.1-jdk17 AS build

WORKDIR /app

COPY build.gradle .
COPY src ./src

RUN gradle build -x test

# Stage 2: Run

FROM openjdk:17-jdk-alpine

WORKDIR /app

COPY --from=build /app/build/libs/*.jar app.jar

ENV JAVA_OPTS="-Xmx512m -Xms256m"

EXPOSE 8080
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar app.jar"]